# Generated by Django 5.1.2 on 2025-01-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='trained_images/')),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('severity_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('recommended_actions', models.TextField()),
                ('prevention_tips', models.TextField()),
                ('emergency_symptoms', models.TextField()),
                ('treatment_options', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='analysis_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='doctor_consultation_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='requires_immediate_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='confidence_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='detected_disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skin_analysis.skindisease'),
        ),
    ]
